
spring:
  data:
    mongodb:
      uri: mongodb://order-food-mongo-srv:27017/auth?directConnection=true
  kafka:
    topic1: order-event
    cancelorder: "cancelorder"
    expireorder: "expireorder"
    consumer:
      group-id: order-service-listeners
    orderexpireconsumer:
      group-id: order-expiration-order-listeners
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties[request.timeout.ms]: 600000
    admin:
      properties:
        bootstrap-servers: kafka-service:9092
    bootstrap-servers: kafka-service:9092
server:
  port: 8072
  error:
    include-message: always
